### ISSUE TITLE
Representation of primitives

### ISSUE THREAD

**Issue by breuleux** [mila-udem/myia#20]
At the moment, primitives are subclasses of `Primitive`, but they are basically empty shells, and instantiated as singletons. Is there a particular reason for this, or could primitives simply be instances of `Primitive`, e.g.

```python
add = Primitive('add', "Addition of two scalars.")
sub = Primitive('sub', ...)
...
```

This would also allow for `node.value is primops.add` instead of `isinstance(node.value, primops.Add)`. I'd rather settle that earlier than later.

**Comment by bartvm** [comment]
The main reason I made them classes so far is so that we can follow a design similar to e.g. the sea-of-nodes implementation described in Click's thesis, which means that each primitive can define things such as algebraic identities (for CSE at parse-time), type inference, etc.
```python
class Add(Primitive):
    def create(self, inputs, graph):
        """Construct application of this primitive with algebraic identities."""
        x, y = inputs
        if isinstance(x, Constant) and isinstance(y, Constant):
            return Constant(x.value + y.value)
        else:
            return Apply([self, x, y], graph)

    def type(self, inputs):
        """Perform type inference.

        Returns intersection of types e.g. float32 & Any -> float32 but
        float32 & float64 -> Bottom (i.e. type error)

        """
        x, y = inputs
        return x.type & y.type
```
The downside of this approach is that the classes will grow relatively big. It looks better than something like this though, which kind of breaks the entire encapsulation principle:
```python
def add_type(node):
    x, y = node.inputs
    return x.type & y.type

# Mapping from primitives to their type inference functions
TYPING = {add: add_type}
```
But maybe we can do something like this (potentially with more sugar) to keep the code in separate files nonetheless: 
```python
def add_type(self, inputs):
    x, y = inputs
    return x.type & y.type
Add.type = add_type
```

**Comment by bartvm** [comment]
Another consideration is parametrized primitives (Theano has these I believe). For example, this addition primitive can cast or not, which changes type inference, but the algebraic identities can be shared.
```python
class Add(Primitive):
    def __init__(self, cast: bool):
        self.cast = cast

    def type(self, inputs):
        if not if x.type & y.type and self.cast:
            return max_precision(x.type, y.type)
        else return x.type & y.type

add = Add(False)
add_with_cast = Add(True)
```

**Comment by breuleux** [comment]
There's also the decorator approach:

```python
@type_inferrer
def add_type(node):
    x, y = node.inputs
    return x.type & y.type
```

I mean, it's not clear whether any "encapsulation principle" really applies here. On one hand you have primitives, on the other you have an array of behaviors and rules associated to them. There are two dimensions here, and code is only linear. So you can either group all of a primitive's rules together, or you can group all of a certain rule's implementations together. Adding new primitives is easier with the former, adding new types of behaviors (like a partial evaluator and whatnot) is easier with the latter. As far as usage patterns go, different methods of the same primitive generally aren't used at the same time, whereas the same method of different primitives are, which suggests it makes more sense to group by method than by primitive (if e.g. we wanted to have all related pointers near in memory, which I will grant isn't really a concern we have).

It also depends on whether there is a simple taxonomy of primitives. A lot of primitives (add, sub, etc.) may share the same type signature, so what do you do with that? Do you make them inherit from the `UniformNumericTyping` class? But you might also have `NeutralElement` and a lot of other shared behaviors, and primitives may then have to inherit from a lot of classes.

I'm not against it necessarily, but I don't think having a class for each primitive is obviously good organization.

> Another consideration is parametrized primitives (Theano has these I believe). For example, this addition primitive can cast or not, which changes type inference, but the algebraic identities can be shared.

Yes, that's a good point, we could have something like that. I'm not sure it's a good idea, though, because it makes primitives more complex, which means more complex type inference, gradients and implementations compared to a different approach like `t = max_precision(x, y); add(cast(x, t), cast(y, t))`. There is also the issue of how the user is supposed to instantiate them in source code to begin with.

There is one class of parameterized "primitives" I think is interesting, which is operations like `GEMM` that are equivalent to a graph of simpler operations, but have to be implemented as a unit. In those cases, type inference and other missing methods, if they are needed, would be implemented by going through the equivalent graph. It might be best to have these be instances of a generic `PrimitiveFromGraph` class, though.

----

Anyhow, if we go with classes, `Add` and so on should probably be singleton classes, such that `Add() is Add()`. It makes it easier to check something is an addition, and it can be used as a dictionary key and so on.

**Comment by breuleux** [comment]
This was resolved in a meeting. See #25.
