### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by datnamer** [mila-udem/myia#42]
Hello,

Looks like an interesting project. Are you planning to use type annotations as part of the user facing type system, or is it just for the backend codebase? 

How about the dispatch macro for extend types? Can a user write their own array or number type and the write a series of dispatch's to extend abstract functions on different combinations of arguments, or will it be more a standard python single dispatch?

**Comment by breuleux** [comment]
Hi,

The annotations are for the codebase, they are processed through mypy to guard against some errors. From a user perspective, we plan to infer types at call time, based on the types of the arguments the user provides (and cache the result of the compilation for these types). This should spare them the need to provide annotations in most situations, although we may parse and use them if they are available.

Support for custom array or number types isn't something we have put much thought into yet, but if/when we support it, expect single dispatch. Again, though, we don't really have a solid or final plan for that kind of advanced feature.

Thanks for the interest!

**Comment by datnamer** [comment]
Understood, thanks!
